security:
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        backend_users : 
            memory:
                users:
                    admin: {password: 'admin', roles: ['ROLE_ADMIN']}
        our_db_provider:
            entity:
                class: App\Entity\Visiteursmedicaux
                property: login
    encoders:
        #Symfony\Component\Security\Core\User\User: plaintext
        App\Entity\Visiteursmedicaux: plaintext

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: lazy

            form_login:
                check_path: security_login
                default_target_path: allFicheFrais

            logout:
                path: security_logout
                target: security_login
            provider: our_db_provider

            # activate different ways to authenticate
            # https://symfony.com/doc/current/security.html#firewalls-authentication

            # https://symfony.com/doc/current/security/impersonating_user.html
            # switch_user: true

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        # - { path: ^/AllFicheFrais/3, roles: ROLE_ADMIN }
        # - { path: ^/profile, roles: ROLE_USER }
