<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOlgzuj5\srcApp_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOlgzuj5/srcApp_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerOlgzuj5.legacy');

    return;
}

if (!\class_exists(srcApp_KernelProdContainer::class, false)) {
    \class_alias(\ContainerOlgzuj5\srcApp_KernelProdContainer::class, srcApp_KernelProdContainer::class, false);
}

return new \ContainerOlgzuj5\srcApp_KernelProdContainer([
    'container.build_hash' => 'Olgzuj5',
    'container.build_id' => 'fa7e36a7',
    'container.build_time' => 1620285735,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOlgzuj5');
