<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container8E4gpHv\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container8E4gpHv/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container8E4gpHv.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container8E4gpHv\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container8E4gpHv\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '8E4gpHv',
    'container.build_id' => '8fc90ac8',
    'container.build_time' => 1620285654,
], __DIR__.\DIRECTORY_SEPARATOR.'Container8E4gpHv');
