<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format'], ['variable', '/', '\\d+', 'code'], ['text', '/_error']], [], []],
    '_wdt' => [['token'], ['_controller' => 'web_profiler.controller.profiler::toolbarAction'], [], [['variable', '/', '[^/]++', 'token'], ['text', '/_wdt']], [], []],
    '_profiler_home' => [[], ['_controller' => 'web_profiler.controller.profiler::homeAction'], [], [['text', '/_profiler/']], [], []],
    '_profiler_search' => [[], ['_controller' => 'web_profiler.controller.profiler::searchAction'], [], [['text', '/_profiler/search']], [], []],
    '_profiler_search_bar' => [[], ['_controller' => 'web_profiler.controller.profiler::searchBarAction'], [], [['text', '/_profiler/search_bar']], [], []],
    '_profiler_phpinfo' => [[], ['_controller' => 'web_profiler.controller.profiler::phpinfoAction'], [], [['text', '/_profiler/phpinfo']], [], []],
    '_profiler_search_results' => [['token'], ['_controller' => 'web_profiler.controller.profiler::searchResultsAction'], [], [['text', '/search/results'], ['variable', '/', '[^/]++', 'token'], ['text', '/_profiler']], [], []],
    '_profiler_open_file' => [[], ['_controller' => 'web_profiler.controller.profiler::openAction'], [], [['text', '/_profiler/open']], [], []],
    '_profiler' => [['token'], ['_controller' => 'web_profiler.controller.profiler::panelAction'], [], [['variable', '/', '[^/]++', 'token'], ['text', '/_profiler']], [], []],
    '_profiler_router' => [['token'], ['_controller' => 'web_profiler.controller.router::panelAction'], [], [['text', '/router'], ['variable', '/', '[^/]++', 'token'], ['text', '/_profiler']], [], []],
    '_profiler_exception' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::body'], [], [['text', '/exception'], ['variable', '/', '[^/]++', 'token'], ['text', '/_profiler']], [], []],
    '_profiler_exception_css' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::stylesheet'], [], [['text', '/exception.css'], ['variable', '/', '[^/]++', 'token'], ['text', '/_profiler']], [], []],
    'connexion' => [[], ['_controller' => 'App\\Controller\\ConnexionController::connexion'], [], [['text', '/connexion']], [], []],
    'inscription' => [[], ['_controller' => 'App\\Controller\\ConnexionController::inscription'], [], [['text', '/inscription']], [], []],
    'allFicheFrais' => [[], ['_controller' => 'App\\Controller\\FicheFraisController::AllFicheFrais'], [], [['text', '/AllFicheFrais/3']], [], []],
    'uneFiche' => [['id'], ['_controller' => 'App\\Controller\\FicheFraisController::uneFiche'], [], [['variable', '/', '[^/]++', 'id'], ['text', '/uneFiche']], [], []],
    'uneFicheModif' => [['id'], ['_controller' => 'App\\Controller\\FicheFraisController::uneFicheModif'], [], [['variable', '/', '[^/]++', 'id'], ['text', '/uneFicheModif']], [], []],
    'getDNFF' => [['id'], ['_controller' => 'App\\Controller\\FicheFraisController::getDNFF'], [], [['variable', '/', '[^/]++', 'id'], ['text', '/getDNFF']], [], []],
    'getDFF' => [['id'], ['_controller' => 'App\\Controller\\FicheFraisController::getDFF'], [], [['variable', '/', '[^/]++', 'id'], ['text', '/getDFF']], [], []],
    'postFF' => [[], ['_controller' => 'App\\Controller\\FicheFraisController::postFF'], [], [['text', '/postFF/']], [], []],
    'postHF' => [['idAvoir1'], ['_controller' => 'App\\Controller\\FicheFraisController::postHF'], [], [['variable', '/', '[^/]++', 'idAvoir1'], ['text', '/postHF']], [], []],
    'security_login' => [[], ['_controller' => 'App\\Controller\\SecurityController::login'], [], [['text', '/']], [], []],
    'security_logout' => [[], ['_controller' => 'App\\Controller\\SecurityController::logout'], [], [['text', '/logout']], [], []],
];
